SET IDENTITY_INSERT [dbo].[Kinds] ON
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (1, 1, N'Зарплата')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (2, 1, N'Аванс')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (3, 2, N'Проценты на НЗ')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (4, 2, N'Дивиденды')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (5, 2, N'Купонный доход')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (6, 3, N'Разработка документации')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (7, 5, N'Топливо')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (8, 5, N'Омывайка')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (9, 5, N'Страховка ОСАГО')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (10, 6, N'Обеды')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (11, 6, N'Мобильный телефон')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (12, 6, N'Обучение')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (13, 6, N'Хобби')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (14, 7, N'Деньги в семью')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (15, 7, N'Детский сад')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (16, 7, N'Питание, хозбыт, лекарства')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (18, 3, N'Спекуляции')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (9025, 9, N'Непредвиденные расходы')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (10018, 8, N'Покупка лампочек')
INSERT INTO [dbo].[Kinds] ([Id], [CategoryId], [Kind]) VALUES (11018, 11, N'Покупка крипты')
SET IDENTITY_INSERT [dbo].[Kinds] OFF
