SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (5, N'Автомобиль')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (9, N'Гараж')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (12, N'Долги')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (8, N'Жилье')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (1, N'Зарплата')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (11, N'Инвестиции и пенсионный фонд')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (6, N'Личные траты')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (10, N'Налоги')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (2, N'Пассивный доход')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (14, N'Прочие доходы')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (13, N'Прочие расходы')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (3, N'Самозанятость')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (7, N'Семья')
INSERT INTO [dbo].[Categories] ([Id], [Category]) VALUES (5016, N'Субсидии')
SET IDENTITY_INSERT [dbo].[Categories] OFF
